### ISSUE TITLE
Marketplace installer via Eclipse taking forever

### ISSUE THREAD

**Issue by mwpowellhtx** [Nodeclipse/packages#3]
I've downloaded offline and it's only something like 30 MB and change, correct? Hung up resolving features, fetching stuff. Barely 5-10% along. Whatever the hang-up is, it's unacceptable. Is there a procedure for installing that offline as contrasted with the marketplace installation?

**Comment by mwpowellhtx** [comment]
So I stand corrected, I'm not sure what the 30 MB archive was. I found the *Enide* offline downloads, and it is an order of magnitude larger. ***Still***, those downloads are moving along, whereas the marketplace installer is taking forever to resolve, etc. Question still stands re: offline installation.

**Comment by mwpowellhtx** [comment]
It is interesting to note the Windows x86 archive is taking forever to download as well. I'm really interested in the x64, I think, which did not take very long. Which I also have the x64 Eclipse, I believe.

**Comment by mwpowellhtx** [comment]
The marketplace install "finished", I get the licenses at the end, I accept them. But I am not getting any project templates or anything like that afterward. What else needs to happen once that is finished?

**Comment by paulvi** [comment]
Network related issue.

On http://www.nodeclipse.org/updates/ see option c) Archive (when Internet is slow, not stable or installing many times)

Follow link to see exact size  
![image](https://user-images.githubusercontent.com/1614482/51438132-d5ffab80-1ce2-11e9-9846-5c1feb3978b3.png)

Usage hints at  http://www.nodeclipse.org/usage

Questions should go to http://www.nodeclipse.org/#support -> SO

**Comment by mwpowellhtx** [comment]
Thank you for the follow up. Yes, I think that was probably the case. It finally did install, and I did download the offline images as a backup plan.
